version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile # 上記で作成したDockerfileのパス
    container_name: laravel_web
    ports:
      - '80:80' # Apache のポート
      - '5173:5173' # Vite の開発サーバーポート (フロントエンド開発時)
    volumes:
      - .:/var/www/html # プロジェクトファイルをコンテナにマウント
    working_dir: /var/www/html
    # dbサービスに依存関係を設定
    depends_on:
      - db

  db:
#    image: mysql:8.0
    container_name: laravel_db
    # 環境変数などDBの設定を記述
    # コンテナの作成に使用するDockerfileのパス
    build:
        dockerfile: "./docker/db/Dockerfile"
        # ホスト側のポート:コンテナ側のポートを指定
    ports:
        - "3307:3306"
    # 環境変数の指定
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_DATABASE=test"
        - "MYSQL_USER=dev"
        - "MYSQL_PASSWORD=dev"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
    # データを永続化するためのボリューム
    - db_data:/var/lib/mysql

# ネットワーク設定（任意）
# networks:
#   laravel-network:
#     driver: bridge

# データを永続化するためのボリューム
volumes:
    db_data:
